// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using store.Repository.Data;

#nullable disable

namespace store.Repository.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20220512140425_Stores Table")]
    partial class StoresTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("store.Domain.Models.v1.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StoreOwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StoreOwnerId");

                    b.ToTable("TBL_STORES");
                });

            modelBuilder.Entity("store.Domain.Models.v1.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email_Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TBL_USERS");
                });

            modelBuilder.Entity("store.Domain.Models.v1.Store", b =>
                {
                    b.HasOne("store.Domain.Models.v1.User", "StoreOwner")
                        .WithMany()
                        .HasForeignKey("StoreOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreOwner");
                });
#pragma warning restore 612, 618
        }
    }
}
